rvm:
  - 1.9.3
  - 1.9.2

bundler_args: --without development darwin debugger

# skip spec/integration tests on travis because it requires an API key
script: "bundle exec rspec --pattern spec/lib/**/*_spec.rb"